version: "3.9"
services:
  traefik:
    image: "traefik:v2.4.5"
    container_name: "traefik"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - frontend

  web:
    build:
      context: ./front-end/
    #ports:
      #- "5000:4201"
    depends_on:
      - computation
      - traefik
    networks:
      - frontend
      - backend

  computation:
    build: ./computation/
    depends_on:
      - traefik
    environment: 
      - "PYTHONUNBUFFERED=1"
    env_file: 
      - ./computation/variables.env
    volumes:
      - ./computation/app:/app
    #ports:
      #- "8080:80"
    networks:
      - frontend

  db:
    image: "mongo:4"
    restart: always
    env_file:
      - ./db/variables.env
      - ./db/api.env
    volumes:
      - ./db/storage:/data/db
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  frontend:
    name: frontend

  backend:
    name: backend
