services:
  traefik:
    ports:
      - "5000:80"
      - "8080:8080"
    command:
      - --api.insecure=true
      - --api.dashboard=true
      #- --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=frontend
      - --entrypoints.http.address=:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"

  web:
    build:
      target: prod
    volumes:
      - ./front-end:/opt/ng
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=http"

  computation:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.computation.rule=Host(`localhost`) && PathPrefix(`/api/`) || PathPrefix(`/docs`)"
      - "traefik.http.routers.computation.entrypoints=http"
      - "traefik.http.middlewares.computation-strip.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.computation-strip.stripprefix.forceslash=false"
      - "traefik.http.routers.computation.middlewares=computation-strip@docker"
      - "traefik.docker.network=frontend"
