services:
  traefik:
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    command:
      - --api.insecure=false
      - --api.dashboard=false
      #- --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=frontend
      - --entrypoints.http.address=:80
      - --entryPoints.http.forwardedHeaders.trustedIPs=127.0.0.1/32, 0.0.0.0/32
      # TODO: figure out why authlib does not compute the correct scheme for the google redirect
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.https.address=:443
      - --entryPoints.https.forwardedHeaders.trustedIPs=127.0.0.1/32, 0.0.0.0/32
      ## Certificate Settings `(Let's Encrypt)
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${CERT_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/certificates/acme.json
    volumes:
      - ./certificates:/certificates
    #labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN_NAME}`)"
      #- "traefik.http.routers.api.service=api@internal"

  web:
    build:
      target: prod
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      # HTTPS router
      - "traefik.http.routers.web-secured.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.web-secured.entrypoints=https"
      - "traefik.http.routers.web-secured.tls=true"
      - "traefik.http.routers.web-secured.tls.certresolver=myresolver"
      - "traefik.http.routers.web-secured.tls.domains[0].main=${DOMAIN_NAME}"

  computation:
    restart: unless-stopped
    environment:
      - "GUNICORN_CMD_ARGS=--forwarded-allow-ips='*'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.computation.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/api/`)"
      - "traefik.http.middlewares.computation-strip.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.computation-strip.stripprefix.forceslash=false"
      - "traefik.http.routers.computation.middlewares=computation-strip@docker"
      - "traefik.http.routers.computation.entrypoints=https"
      - "traefik.http.routers.computation.tls=true"
      - "traefik.http.routers.computation.tls.certresolver=myresolver"
      - "traefik.http.routers.computation.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.docker.network=frontend"

  db:
    ulimits:
      nofile: 40960
      core: 100000000
      memlock: 100000000
    labels:
      - "traefik.enable=false"

networks:
  backend:
    internal: true