services:
  traefik:
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    command:
      - --api.insecure=false
      - --api.dashboard=false
      #- --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=frontend
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      ## Certificate Settings (Let's Encrypt)
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${CERT_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/certificates/acme.json
    volumes:
      - ./certificates:/certificates
    #labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN_NAME}`)"
      #- "traefik.http.routers.api.service=api@internal"
    labels:

      - "traefik.http.middlewares.testHeader.headers.framedeny=true"
      - "traefik.http.middlewares.testHeader.headers.sslredirect=true"
      - "traefik.http.middlewares.testHeader.headers.sslHost=`${DOMAIN_NAME}`"
      - "traefik.http.middlewares.testHeader.headers.sslProxyHeaders=true"
      - "traefik.https.middlewares.testHeader.headers.sslHost=`${DOMAIN_NAME}`"
      - "traefik.https.middlewares.testHeader.headers.sslProxyHeaders=true"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"

  web:
    build:
      target: prod
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      # HTTPS router
      - "traefik.http.routers.web-secured.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.web-secured.entrypoints=https"
      - "traefik.http.routers.web-secured.tls=true"
      - "traefik.http.routers.web-secured.tls.certresolver=myresolver"
      - "traefik.http.routers.web-secured.tls.domains[0].main=${DOMAIN_NAME}"

  computation:
    restart: unless-stopped
    environment:
      - "GUNICORN_CMD_ARGS=--forwarded-allow-ips='*'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.computation.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/api/`)"
      - "traefik.http.middlewares.computation-strip.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.computation-strip.stripprefix.forceslash=false"
      - "traefik.http.routers.computation.middlewares=computation-strip@docker"
      - "traefik.http.routers.computation.entrypoints=https"
      - "traefik.http.routers.computation.tls.certresolver=myresolver"
      - "traefik.docker.network=frontend"
