services:
  traefik:
    ports:
      - "80:80"
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --api.dashboard=true
      #- --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=frontend
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      ## Certificate Settings (Let's Encrypt)
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
      - --certificatesresolvers.mytlschallenge.acme.email=${CERT_EMAIL}
      - --certificatesresolvers.mytlschallenge.acme.storage=/certificates/acme.json
    volumes:
      - ./certificates:/certificates
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.api.service=api@internal"

  web:
    build:
      target: prod
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.web.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.web.entrypoints=http"
      # HTTPS redirector
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
      - "traefik.http.routers.web.middlewares=redirect-https"
      - "traefik.http.routers.web-secured.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.web-secured.entrypoints=https"
      - "traefik.http.routers.web-secured.tls.certresolver=mytlschallenge"

  computation:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.computation.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/api/`) || PathPrefix(`/docs`)"
      - "traefik.http.routers.computation.entrypoints=https"
      - "traefik.http.routers.computation.tls.certresolver=mytlschallenge"
      - "traefik.http.middlewares.computation-strip.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.computation-strip.stripprefix.forceslash=false"
      - "traefik.http.routers.computation.middlewares=computation-strip@docker"
      - "traefik.docker.network=frontend"
